### ISSUE TITLE
OSR multi-echo community meeting planning

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana-ohbm-2020#2]
@smoia is set to lead: "Past, Present and Future of Open Science (Emergent session): Multi-Echo (fMRI) Community meeting" https://github.com/ohbm/osr2020/issues/51 in a few days.
Now that we've seen a bunch of these sessions, we should talk a little bit about how we want to organize this. At past OHBMs, we've gone in with very little lecture-style material and we try to have as much a discussion as possible. That seems ideal to me, but we'd need some planning to decide how to do that within the restrictions of the format.

As in past years, I think it makes sense to have an open google doc for meeting notes that we can share and edit live. We can make it world editable and lock it down after the meeting. Is something besides google docs better for nations with access restrictions?

Do we want some actual slides or just have a conversation?

Some sessions have had Zoom windows inside of crowdcast. We could then share the zoom link (with a waiting room) and that would let people more spontaneously join.

If we stick with just crowdcast how/who should manage who will be allowed on the screen at various points?

@emdupre @tsalo @eurunuela @jbteves

**Comment by tsalo** [comment]
>Is something besides google docs better for nations with access restrictions?

I think people have been using Etherpad in the OSR, unless I'm misremembering?

**Comment by handwerkerd** [comment]
Etherpad would work well for this.
Who is planning to attend this meeting live? Other comments on my questions above. My big concern is that it seems like many of these online OSR meetings do have a bit more structure than we've had at past OHBMs, so it would be good to go in with a bit more of a plan.

Also tagging @62442katieb

**Comment by smoia** [comment]
Sorry for the late reply, I needed the weekend off screen.
Thank you for the good pointers!

Tagging @jsheunis since he might be interested in the emergent session and can give us more information on the format.

@handwerkerd what countries are you thinking about? Remember that this session will unluckily take place during the night for the APAC hub, so we can probably work with whatever we want and then move everything to Etherpad or GitHub (even here, cross-linking it in the GitHub issue of the meeting - that I can't share now due to [GitHub being a unicorn](https://github.com/503.html) in [this moment](https://www.githubstatus.com/)).

I was thinking about creating a Google form to collect the emails of the participants though, so it's good to think about an alternative.

As for a plan, here's a proposal:
- we introduce the session and its scopes (about 5-10 minutes)
- a representative from tedana (@emdupre? @handwerkerd? @tsalo?) presents the _community_ component of tedana (general aim, documentation, what it means/doesn't mean to be part of this community, the mailing list). About ten minutes?
- we open a round table asking the participants for their interest in joining/(re-)creating a ME community, asking if there's any trouble in using tedana as the main platform and if not, if there are (and which are) components that should be introduced / strengthened / clarified in order to ease the growth of the community (and tedana). Half an hour.
- we itemise actions, find volunteers to take care of them and eventually invite to a future community meeting in three to six months. (10 to 15 minutes).

Personally, I don't have incredibly ambitious goals for this meeting - especially for the format it's going to be forced into.
One tool that I think will start making the difference between a community and the lack of it is a mailing list, so if we manage to make it participated, stable, and of general interest, possibly with more people taking care of it (mainly because we should expect an increase in traffic), I'll be happy with the outcome.

If there are other goals that we want to reach, I'm not against presenting them, but remember that we will need to find volunteers to take care of them if it's something we don't have implemented yet. So, for instance, I won't actively promote a community paper since I know already I can't take lead on the process at the moment. If anyone else thinks they can and want to do it, I'm going to strongly support it.

**Comment by jsheunis** [comment]
Hi everyone

I'm keen to join the meeting and can also give some more info about the tech we use in the OSR. There are two options:

1. *Everything directly via Crowdcast*. The main limitation here is 4 screens live at any moment, including the OSR admin. I.e. 3 tedana community members, or 2 + a shared screen. There will be an admin OSR team member to handle to process of pulling people on and off screen depending on your preference throughout the session. Anyone from the audience can join  in this way, or they can opt for just typing in the chat. The great thing about Crowdcast is it's interactivity, and the speakers being able to respond immediately to community input.
2. *Zoom meeting*, which is broadcast via Crowdcast. The main pro of this option is the fact that zoom allows many more people on screen at the same time. However, we've noticed that limiting the amount of people to below 10 helps a lot with keeping the discussion productive. The main drawback of this option is that there is about 30-40 second delay between anything happening on zoom and that showing up via Crowdcast.

If you're envisioning this running in a similar fashion to the BIDS townhall meeting, I would suggest going for pure Crowdcast. I also like the suggestion of Etherpad (since AFAIK it's not blocked in some countries like Google). We also create a mattermost channel for each OSR emergent that we point people to during the meeting.

Let me know if something in my explanation isn't clear. 

In either case there will be an OSR team member to help you in real-time with all admin/logistics related to the meeting.

**Comment by emdupre** [comment]
Thanks, everyone ! I (personally) like the idea of a crowdcast session with an etherpad doc. Unfortunately, I had missed the new timing and I have a lab meeting then, so I won't be able to make it. 

I want to tag in a few folks who may not know about the session and it would be great to have feedback from: @lmwilambwe, @agahkarakuzu, @giuliabaracc. Would be great to get your feedback either at the session or in the etherpad doc !

**Comment by handwerkerd** [comment]
@emdupre We're currently scheduled for 15:00 EST. It looks like no one is scheduled for 14:00EST (and I think @smoia said he's prefer an earlier time. Is it still possible to shift earlier? Would that make it possible for you to attend?

From the comments so far, it sounds like ether pad makes sense. Since etherpad lives on many sites, has there been a preferred one for OSR?

The big advantage of Zoom is, if a bunch of us plan to be present, we can just pop in and off the Zoom call as we're relevant, without host intervention. We can also relatively easily invite a few more people to pop in and out. That said, if we're not going to have >4 on the screen at any one time and there is a lag, then we should stick to crowdcast.

I wanted to respond now before it becomes eventing in Europe, but I'll think about agenda a bit more later, when I'm not also parenting.

**Comment by emdupre** [comment]
Yes, my meeting runs 3-4p Eastern, so I could do earlier, but I also don't
want to throw a wrench in scheduling last minute ! I know how difficult it
is to coordinate these things.

So if the change is easy, great ! If it's complicated / at all
inconvenient, let's stick with the current timing 😸

Le lun. 29 juin 2020 10 h 49, handwerkerd <notifications@github.com> a
écrit :

**Comment by jbteves** [comment]
If we shift earlier I probably won't make it at all, but it's certainly preferable for @emdupre to make it over me. I agree with crowdcast + ether based on this thread.

**Comment by smoia** [comment]
@handwerkerd any news? I should give a feedback in ten minutes or so...

**Comment by handwerkerd** [comment]
Given it might cause more headaches for the OSR coordinators and some people may have already put the time on their calendar, I'd now lean towards not changing the time. (If others disagree and think we should change, I won't protest, but we should make that decision ASAP). That said, this may make us one of the few OSR sessions led by all male faces. I think one of us should mention this directly, and make an explicit statement welcoming diverse contributors. I can do it & I'm also ok if someone else wants to make such a statement.

Working off of @smoia's schedule from an earlier comment, I'd make a few edits and suggested more specific names assuming @emdupre can't attend live

Unless anyone disagrees, I'm going to send out a tweet in a couple of hours announcing the session and inviting any other multi-echo software developers or users to briefly speak at the meeting. (We can also welcome people attendees to speak at the meeting)

* We introduce the session and its scopes (Stefano)
* 5 minutes What is multi-echo fMRI & why care, & a brief intro to tedana as software I'm willing to do this. (Given the recurring rabbit theme in the OSR, I have an idea how to do this using rabbit balloon animals. My idea may work well or fail spectacularly.)
* A representative from tedana (@tsalo, @jbteves, or me) presents the community component of tedana (general aim, documentation, what it means/doesn't mean to be part of this community, the mailing list). About 5 minutes?
* Allow others to type or speak about software or multi-echo work they've done in the past year (ideally 1-3 minutes per speaker and we'll read out any noteworthy stuff placed in the text documents) @smoia would be the onscreen moderator for this section? @handwerkerd would monitor online feeds and either verbally comment or prompt Stefano.
* We open a round table asking the participants for: (Cut off 5-10 before the hour, if we last that long) 
      * Input on the current tedana community. Things they like, things missing, things that could be better components that should be introduced / strengthened / clarified in order to ease the growth 
      * Any trouble using tedana as a communal platform?
      * Interesting in more actively contributing to a ME community at tedana or creating community resources elsewhere?
* We itemize actions, find volunteers to take care of them and eventually invite to a future community meeting in three to six months. (10 to 15 minutes).


Thoughts?

**Comment by smoia** [comment]
@handwerkerd I agree on making a disclaimer, I can do it without any problem too (we can also talk about what such disclaimer should be together). Let's remember that we are trying to be inclusive and diverse, but sometimes it's not possible to do so (I also wouldn't know who else can take the place of @emdupre, especially last minute, since as far as I understood @KirstieJane will not attend the meeting).

I would skip the 3 minutes pitches from the participants this time: we don't know if people can do it, if they can stay in time, and with the screen jumps in crowdcast you need to consider thirty seconds/a minute just for the change. If you consider that the part you attributed time to are already 20 to 30 minutes, that leaves 30 minutes for everything else. If you have 5 people presenting themselves it's already about 20 minutes, which leaves only 10 minutes for what I think should be the main topic of the meeting.

We can invite people to present themselves in the chat and if they want to speak they will be invited again to present themselves and (shortly) their work. Otherwise the risk is doing a round table of presentation ending up without enough time to take decisions or get feedback. The thing that I got from other crowdcast sessions is that it's better to optimise screen changes, putting together two or three points rather than having people popping up two or three times.

One thing that I would do is organise a part of the document we're going to create and use as a "nametag", i.e. Name+surname/email/affiliation/field of work in ME. Probably we should have a way to submit the email in a non-public manner (ideas on how to do so without a google form?). This should give enough space for people to present themselves and be "seen".

**Comment by handwerkerd** [comment]
I think it would help to tweet something out soon so that we can get a sense if anyone else would definitely like to speak. I don't think we'll get too many responses, but any responses we do get would help us plan.

I also want to be clear that the issue is, if @emdupre and @KirstieJane aren't there, the rest of our core team is currently male. We can't change the optics when the optics represent reality, but we can acknowledge the optics, make clear that everyone is welcome to contribute, and work to get more diverse contributors.

**Comment by smoia** [comment]
Totally agree - sorry if my message seemed to go in a different direction.

**Comment by giuliabaracc** [comment]
Hi. Thanks @emdupre for mentioning us here. I will be there and I believe, Laetitia and Roni from my lab will also join - we all work with multi-echo data.

**Comment by smoia** [comment]
@handwerkerd do you want to send the twitter? I think that the label "tweeted" in ohbm/osr2020#51 means they tweeted our meeting. We could retweet it again - no idea when it was tweeted though.
I need to insist on *not* having a pitch moment that is separated from a general intervention about the reason we're having a meeting - unless the main reason is to catch up, in which case I'll revise the goals of the meeting itself and suggest we _don't_ discuss about the community or we skip other proposed parts. Not pitching doesn't mean not being able to speak - on the contrary we should be very inclusive and welcoming of any kind of intervention, and I really believe reducing the number of screen changes to a minimum will help.
I'd also clarify that *not* answering to the tweet doesn't mean not being able to get screen time during the meeting itself. We can use the "ask a question" box to collect a ordered list of speakers - should be more feasible than having to keep track of the chat.
This said, I need to dedicate myself to another project for the rest of the night - I'll keep following the discussion here, but probably won't reply until tomorrow.

@giuliabaracc great! Would any (or all) of you like to speak during the meeting? We need a good feedback from the community!

**Comment by handwerkerd** [comment]
It looks like @OHBM_Open_Science has tweets for many sessions, that include links to the appropriate links, but I don't see one for our session. I'll ask there so that I can retweet from them. If I don't hear back, I'll send out a tweet soonish. Just to be clear, the plan is to promote the event, it seems like we're not moving the time, and I will say others are welcome to speak?

I'll defer to you regarding pitches. I guess the plan is to welcome people to say who they are, what they do, and their thoughts on community, but not to have everyone to pitch their specific methods?

Welcome @giuliabaracc!

**Comment by giuliabaracc** [comment]
Sure! Roni has been working with these types of data for much longer than myself and she would be happy to provide some feedback. Laetitia and I would also be happy to share our experiences.

**Comment by smoia** [comment]
Hey Dan - I really need to concentrate for an hour or so, but if you can, can we have a quick zoom chat later? I think that would fasten up things and clarify better than text? 

Stefano Moia 

--- 
PhD student @ BCBL 
www.bcbl.eu 

Tel: +34 943 309 300 

Legal disclaimer/Aviso legal/Lege-oharra: www.bcbl.eu/legal-disclaimer

**Comment by handwerkerd** [comment]
After speaking to @smoia, I've started to structure https://etherpad.wikimedia.org/p/OBHM-OSR-multiechofMRI as a place to take notes during the meeting. In past years, we went around the room hearing interests updates from everyone. That's more difficult this year so we'll encourage everyone to add information to that doc in advance or during the meeting. At this point, suggestions for structuring the document are also welcome.

**Comment by handwerkerd** [comment]
@mrikasper Making sure you know about the Multi-echo community meeting at online OHBM.

**Comment by smoia** [comment]
I started a presentation for the meeting [here](https://docs.google.com/presentation/d/1TCsaru-eSwhiIb5z7FmctutX-ngQ5-rqwuM6xmrags4/edit?usp=sharing). Everyone, feel free to add slides or comment, or to create another set!

**Comment by jbteves** [comment]
Thanks for putting this together, @handwerkerd and @smoia. I may actually be able to make it after all. FYI @smoia people will need to request edit access on your google slides.

**Comment by smoia** [comment]
@jbteves it's on purpose, but good to specify that if someone wants to add something, they can ask the permission!

**Comment by handwerkerd** [comment]
@smoia and others. I'm realizing we may want to make liberal use of polls during the presentation.
Poll 1:
Familiarity with Multi-echo fMRI
* Don't know much yet
* Know what it is but haven't used
* Primarily a user of multi-echo fMRI
* Working on multi-echo fMRI methods development

Using tedana.readthedocs.io as a general multi-echo community resource
* Fine with me, but I probably won't contribute
* Fine with me, but I'd need more help to contribute
* Fine with me, and I do contribute
* I'd prefer another location

Multi-echo fMRI community meetings
* Once a year at OHBM is enough?
* ~2 times per year
* ~4 times per year

Also, looking at the slides, I think we'll really want to show what has been added to tedana.readthedocs.io before we start getting into a discussion about it. If you're screen sharing, that could be from you, but I'm also fine doing it.

**Comment by smoia** [comment]
@handwerkerd we can switch screen sharing (it's not optimal, but we can). You can also add things to the slides and ask me to change for you!

**Comment by smoia** [comment]
@jsheunis are you going to make the polls or can we make them ourselves?

**Comment by handwerkerd** [comment]
Great hosting job @smoia! That was fun, but more exhausting & stressful than hosting an in-person meeting. I'm not sure how the people who are hosting many of these are holding up.
@emdupre If you end up watching later, could you read the etherpad in advance and add anything there that seems relevant, but missing? If you don't, don't worry.

**Comment by smoia** [comment]
I have to admit I normally sweat less during talks and presentations than I did now :sweat_smile: 
Great job everyone, thank you for joining on screen (@dowdlelt next time I'm going to catch you too)!
I think it went well, and we got some good tips to work with, didn't we?

**Comment by dowdlelt** [comment]
I think there was a lot of great feedback and things to think about. No doubt because of the excellent hosts, and the leading questions. I had trouble joining so I missed most of the balloon animal fun, alas. 

I'm certainly sensitive to the "can we trust it" question, and the corollary "help me convince my PI it's safe"problem. It's a thorny issue, because no one disagrees that there are better ways to collect data, but some people want to go fast, others higher res, and multiecho just adds another wrinkle. Convincing people requires so many tasks to be considered, and best practices used in each sequence. Forget consciousness, this is the hard problem.

**Comment by jsheunis** [comment]
@handwerkerd @smoia that was a great and engaging session, well done! If you were stressed or anything, that didn't show at all.

**Comment by tsalo** [comment]
@dowdlelt This is why I like the idea of providing common protocols and sharing the strengths and weaknesses of each one- preferably with at least a little actual data to play with.

**Comment by smoia** [comment]
@dowdlelt I totally agree with you (and with what @cassgvp was saying). The hard issue here is: we can develop and research as much as we want, but if we don't show clinical practice can benefit, we're not going anywhere. That also means making our tools easier to use though!

**Comment by dowdlelt** [comment]
I'll disagree slightly - if we could get "basic science" on board, computational type folks, sensation and perception folks - then I think we could make a lot of headway. Of course - the goal is clinical utility - but I think following a path that fMRI in general is trying to take - the one that threads from basic science to clinical work - is not a bad idea. The struggle to me seems to be that even the people "with nothing on the line" doing perception work in healthy controls are not even that interested in multiecho. 
A quote, as an example - "If you show me that it is better, I will use it" from a cognitive fmri researcher. Some of these folks don't care so much that there are complexities - or other difficulties - they just want to get the "best" data possible. Of course "better" is a difficult metric - Better for what?
